{"uuid": "4fc5e99e-dd3c-4737-b94f-7063d780a0f1", "counter": 36, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: from_text() takes at most 5 arguments (9 given)\u001b[0m\r\n\u001b[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\\\", line 114, in <module>\\n    _ansiballz_main()\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\\\", line 106, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\\\", line 49, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\\"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\\\", line 118, in <module>\\n  File \\\"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\\\", line 115, in main\\n  File \\\"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\\\", line 81, in ensure\\n  File \\\"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\\\", line 61, in build_zone\\nTypeError: from_text() takes at most 5 arguments (9 given)\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "d1f9c7f9-2385-44ba-b75c-1fd8af479794", "event": "runner_on_failed", "event_data": {"playbook": "integrations.yml", "playbook_uuid": "e1f24ff2-a9a7-4f14-8fcf-64f7d063ca9b", "play": "Run tests(s)", "play_uuid": "1c1b0dec-55e8-99f5-9a25-000000000009", "play_pattern": "containers", "task": "TEST1 | create zone", "task_uuid": "1c1b0dec-55e8-99f5-9a25-00000000003a", "task_action": "dnszone", "task_args": "", "task_path": "/home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml:10", "host": "dnszone_dnszone_1", "remote_addr": "dnszone_dnszone_1", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 61, in build_zone\nTypeError: from_text() takes at most 5 arguments (9 given)\n", "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576351.9907367-196274380833914/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_3thD7u/__main__.py\", line 61, in build_zone\nTypeError: from_text() takes at most 5 arguments (9 given)\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "ignore_errors": null, "event_loop": null, "pid": 23262}, "pid": 23262, "created": "2019-08-12T02:19:13.419524", "parent_uuid": "1c1b0dec-55e8-99f5-9a25-00000000003a"}